#   ___         _      ___            _ _ _          _____    _                 ___ _           _
#  | _ ) ___ __| |_   / _ \ _  _ __ _| (_) |_ _  _  |_   _|__| |_____ _ _  ___ | _ \ |_  _ __ _(_)_ _
#  | _ \/ -_|_-<  _| | (_) | || / _` | | |  _| || |   | |/ _ \ / / -_) ' \(_-< |  _/ | || / _` | | ' \
#  |___/\___/__/\__|  \__\_\\_,_\__,_|_|_|\__|\_, |   |_|\___/_\_\___|_||_/__/ |_| |_|\_,_\__, |_|_||_|
#                                             |__/                                        |___/
# _____________________________________________________________________| Flares.dev | discord.flares.dev

enable_debug: false

allow_bstats: true

select_locale: en.yml

storage:
  # This is used to not spam the connection with a lot of reads, but if you want to disable this feature set the cache_time to 0
  cache_time: 5
  # Choose (file|mysql|sqlite)
  type: sqlite
  # Database drivers available only for database storage type
  driver: MySql
  mysql:
    host: "localhost"
    port: 3306
    database: "test"
    username: "root"
    password: ""
    table: "flaretokens"
    flags: "useSSL=false&characterEncoding=utf8"

first_join_give_tokens: 0

rotating_shop_time_format: "%min% min %sec% sec"

shop:
  # Rather if you want to have the shop enabled.
  enable: true
  # This could use the mobcoins base command (ex: /mobcoins) to open the shop.
  open_command: "tokenshop"
  # Add the shop file name (Example for "shop.yml" just shop). (Shops are added in the shop folder)
  main_shop: main