name: TMTokens
version: 3.0.4
main: net.devtm.tmtokens.TMTokensPlugin
author: TMDevelopment
description: One of the best tokens plugin available on the market
website: devtm.net
api-version: 1.13
commands:
  tokens: